name: Extract 720pstream Events

on:
  workflow_dispatch:    # allow manual trigger
  schedule:
    - cron: "0 * * * *"   # run every hour

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run extractor
        run: |
          cd script.module.jetextractors/lib
          # Run as module to respect relative imports
          python -m jetextractors.plytvsites.stream720p > ../../output.m3u8

      - name: Upload result artifact
        uses: actions/upload-artifact@v4
        with:
          name: extracted-m3u8
          path: output.m3u8
