name: Extract 720pStream

on:
  workflow_dispatch:   # run manually from Actions tab
  schedule:
    - cron: "0 * * * *"  # run every hour

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run extractor
        run: |
          python 720pstream.py

      - name: Upload m3u8 file
        uses: actions/upload-artifact@v4
        with:
          name: stream-links
          path: output.m3u8
